import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./components/Footer";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import ImageKitProvider from "./providers/ImageKitProvider";
import { Toaster } from "react-hot-toast";
import LocaleSync from "./components/LocaleSync"; // <-- Add this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elodia Beauty & Spa",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <LocaleSync locale={locale} /> {/* Add here */}
          <Navbar />
          <ImageKitProvider>{children}</ImageKitProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
